import { Inter_Tight } from 'next/font/google'
import './globals.css'
import Image from 'next/image'
import Link from 'next/link'

const interTightSans = Inter_Tight({
  variable: '--font-inter',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${interTightSans.variable}  antialiased p-5 mx-auto gap-3`}
      >
        <Link href="/">
          <div className="w-20 aspect-square px-0 mx-6 ">
            <Image
              width={32}
              height={32}
              src="/notes_logo.png"
              alt="logo"
              className="w-full h-full object-cover"
            />
          </div>
        </Link>

        {children}
      </body>
    </html>
  )
}
